
name: CI

on:
  push:
    branches: [ "main" ]


  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: java version
      run: java -version
    - name: maven version
      run: mvn --version
    - name: python version
      run: python --version
    - name: docker version
      run: docker -v

